### PR TITLE
fixing issue 68 "summary or text is required"

### PR DESCRIPTION
**Pull request by Anjana-dyna**
Modified the default Microsoft Teams Message card template as:
- Edited the summary section to fill the value to avoid errors when sending it to Microsoft Teams. 
- Edited to replace underscore(_) to blank.

### CODE REVIEW

**Comment by Knappek** [comment]
@Anjana-dyna  thanks for your contributions. I commented some stuff, the rest looks good.

**Comment by Anjana-dyna** [comment]
> @Anjana-dyna thanks for your contributions. I commented some stuff, the rest looks good.

I will try if I could contribute further.
Will you merge this PR for now? Is that fine?

**Comment by Knappek** [comment]
@Anjana-dyna as commented, I don't want to remove the `.CommonLabels.Alertname` and replace it with `.CommonLabels.cluster`. This might solve your specific use case but not for everyone, moreover it could break things for others using `.CommonLabels.Alertname`.

**Comment by Anjana-dyna** [comment]
> @Anjana-dyna as commented, I don't want to remove the `.CommonLabels.Alertname` and replace it with `.CommonLabels.cluster`. This might solve your specific use case but not for everyone, moreover it could break things for others using `.CommonLabels.Alertname`.

Okay. Then it's fine.

**Comment by Knappek** [comment]
@Anjana-dyna this PR can be closed, correct?

**Comment by Anjana-dyna** [comment]
> @Anjana-dyna this PR can be closed, correct?

Yes, we can close it.
Sorry for the delay. I will do it right now.

**Comment by anopperl** [comment]
Hello, I am trying to use "prometheus-msteams".  it works perfectly with the first alert. but after the first alert, I am getting an error  
     prometheus-msteams      | {"caller":"logging.go:25","err":null,"level":"debug","response_message":"Summary or Text is required.","response_status":400,


my docker compose for  prometheus-msteams

  prometheus-msteams:
    image: quay.io/prometheusmsteams/prometheus-msteams
    container_name: prometheus-msteams
    restart: unless-stopped
    #volumes:
    #    - ./prometheus-msteams/default-message-card.tmpl:/default-message-card.tmpl
    environment:
        - TEAMS_INCOMING_WEBHOOK_URL=https://outlook.office.com/webhook/6d573443-c34d-49ae-8f8c-afd64f2743c2@64604894-f03a-4a39-ad2c-ae1c0ce70a0c/IncomingWebhook/58714ff293524cb1b18793591707a970/0cfb80d5-a685-459e-a126-9d99e7fe990c0
        - TEAMS_REQUEST_URI=alertmanager
        #- TEMPLATE_FILE="./default-message-card.tmpl"
    expose:
      - 2000
    ports:
      - 2000:2000
    restart: unless-stopped  
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "monitoring"
 

alert manager config :


global: 
  resolve_timeout: 10s
receivers: 
  - 
    name: prometheus-msteams
    webhook_configs: 
      - 
        send_resolved: true
        url: "http://prometheus-msteams:2000/alertmanager"

route: 
  
  group_interval: 1m
  group_wait: 5s
  receiver: prometheus-msteams
  repeat_interval: 1m

**Comment by bzon** [comment]
@anopperl can you provide the whole JSON logs from starting when a new request is received? Please redact your webhook URL too.

**Pull request closed without merging**
