### PR TITLE
JSON escape all strings data in alertmanager notify.WebhookMessage

### PR DESCRIPTION
**Pull request by AnandDevan**
This will help parsing the string returned by the template execution

### CODE REVIEW

**Comment by AnandDevan** [comment]
@Knappek I am trying a different route to solve the JSON parsing errors we have been having. Please take a look and help validate this work.
I would also appreciate if we could put together some test data. I've been testing with: newline, single quote, greater than sign. These have caused errors previously

**Comment by AnandDevan** [comment]
I tested with this alert rule and it flows all the way from prometheus to proxy to teams 
```  rules:
  - alert: Scrape failed
    expr: up == 0
    for: 5s
    labels:
      severity: Low
      alert_team: team
      service: unknown
    annotations:
      description: |
            "Scrape 'target' \t   {{ $labels.instance }} is not_reachable by prometheus.
            Please run telegraf, and expose port 9273 with security group rules.
            Fix to monitor for CPU, memory, disk and network usage"
      summary: |
            "Failed scrape_job.
      
            Ensure target is up"
```
image

**Comment by AnandDevan** [comment]
@Knappek Can you look at this proposed PR to make json formation in the template more robust

**Comment by Knappek** [comment]
@AnandDevan I'm sorry that I currently reply very late, I'm having lots of work to do atm. But we will get to your PR soon.

**Comment by bzon** [comment]
LGTM. I will also merge this change to #84 and make a release for them together.

Thanks @AnandDevan 🎉

**Pull request merged**
